[tool.ruff]
line-length = 120
target-version = "py39"
include = ["src/**/*.py", "tests/**/*.py"]

[tool.ruff.format]
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = false