name: Feature Request
description: Suggest a new capability or improvement
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: "Add automatic differentiation engine"
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Implementation Notes
      description: Technical approach, key challenges, or references
      placeholder: |
        - [ ] Add Tensor class
        - [ ] Support backward() with computational graph
        - [ ] Add examples in docs
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
    validations:
      required: true