name: PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pr_agent_job:
    if: |
      (github.event_name == 'pull_request')
    
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          config.model: gpt-4.1
          config.fallback_models: '["gpt-4.1-mini"]'
          github_action_config.auto_review: "true"
          github_action_config.auto_improve: "true" 
          github_action_config.auto_describe: "false"
          github_action_config.pr_actions: '["opened", "synchronize", "reopened", "ready_for_review"]'